spring:
  application:
    name: user-center
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aaron
    username: root
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
#  sql:
#    init:
#      schema-locations: classpath:db/schema-h2.sql
#      data-locations: classpath:db/data-h2.sql
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDeleted # Global logic delete field
      logic-delete-value: 1 # logic deleted val
      logic-not-delete-value: 0 # logic not deleted val
